services:
  - type: web
    name: crop-irrigation-ml-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
